[versions]
jetwhale = "1.0.0-alpha03"
mavenPublish = "0.36.0"

# kotlin
kotlin = "2.3.10"
ksp = "2.3.4"
kotlinDsl = "6.4.2"
kotlinxSerializationJson = "1.10.0"
kotlinxCollectionsImmutable = "0.4.0"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"

# android
androidGradlePlugin = "9.0.1"
androidxCoreKtx = "1.17.0"
androidxActivity = "1.12.4"

autoServiceKsp = "1.2.0"
autoServiceAnnotations = "1.1.1"

jetbrainsCompose = "1.10.1"
material3 = "1.11.0-alpha03"
material3Adaptive = "1.3.0-alpha05"
navigation3 = "1.0.0-alpha06"
lifecycle = "2.9.6"
lifecycleViewModelNavigation3 = "2.10.0-alpha08"
soil = "1.0.0-alpha15"
rin = "0.4.0"

androidxDatastore = "1.2.0"
metro = "0.11.1"
mokkery = "3.2.0"
ktor = "3.4.0"

logback = "1.5.32"
kermit = "2.0.8"

aboutLibraries = "13.2.1"
spotless = "8.2.1"

[libraries]
# Gradle Plugins
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxSerializationGradlePlugin = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
jetbrainsComposeGradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "jetbrainsCompose" }
composeCompilerGradlePlugin = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
metroGradlePlugin = { module = "dev.zacsweers.metro:dev.zacsweers.metro.gradle.plugin", version.ref = "metro" }
androidKotlinMultiplatformLibraryGradlePlugin = { module = "com.android.kotlin.multiplatform.library:com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "androidGradlePlugin" }
mavenPublishGradlePlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublish" }

# kotlin
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# kotlinx
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinxCollectionsImmutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

# androidx
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidxActivityKtx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidxDatastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastore" }

# compose
jetbrainsComposeRuntime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrainsCompose" }
jetbrainsComposePreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "jetbrainsCompose" }
jetbrainsComposeResources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrainsCompose" }
jetbrainsComposeMaterialIconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version = "1.7.3" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
rin = { module = "io.github.takahirom.rin:rin", version.ref = "rin" }

# navigation3
navigation3Ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
navigation3Adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "material3Adaptive" }
lifecycleViewModelNavigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewModelNavigation3" }

# lifecycle
lifecycleRuntimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

# soil
soilQueryCore = { module = "com.soil-kt.soil:query-core", version.ref = "soil" }
soilQueryCompose = { module = "com.soil-kt.soil:query-compose", version.ref = "soil" }
soilReacty = { module = "com.soil-kt.soil:reacty", version.ref = "soil" }

# ktor
ktorServerWebSockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktorServerNetty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktorServerTestHost = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientJs = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktorClientDarwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktorClientWinHttp = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }
ktorClientCurl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktorClientWebSockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktorClientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# logging
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

aboutLibrariesComposeM3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
aboutLibrariesCore = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }

autoServiceKsp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "autoServiceKsp" }
autoServiceAnnotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoServiceAnnotations" }

[bundles]
gradlePlugins = [
    "kotlinGradlePlugin",
    "jetbrainsComposeGradlePlugin",
    "composeCompilerGradlePlugin",
    "metroGradlePlugin",
    "kotlinxSerializationGradlePlugin",
    "androidKotlinMultiplatformLibraryGradlePlugin",
    "mavenPublishGradlePlugin"
]
navigation3 = [
    "navigation3Ui",
    "navigation3Adaptive",
    "lifecycleViewModelNavigation3"
]
ktorServer = [
    "ktorServerWebSockets",
    "ktorServerNetty",
    "ktorSerializationKotlinxJson",
]
ktorClient = [
    "ktorClientCore",
    "ktorClientCio",
    "ktorClientWebSockets",
    "ktorSerializationKotlinxJson",
    "ktorClientLogging"
]

[plugins]
# kotlin
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinDsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlinDsl" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# android
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }

# compose
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }

aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

# conventions
compose = { id = "compose" }
jvm = { id = "jvm" }
multiplatform = { id = "multiplatform" }
serialization = { id = "serialization" }
debuggerComposeFeature = { id = "debugger-compose-feature" }
publish = { id = "publish" }
