[versions]
jetwhale = "0.0.1-alpha01"

# kotlin
kotlin = "2.2.20"
kotlinDsl = "6.4.1"
kotlinxSerializationJson = "1.9.0"
kotlinxCoroutines = "1.10.2"

# android
androidGradlePlugin = "8.13.2"

ktor = "3.3.3"
kermit = "2.0.8"

[libraries]
# Gradle Plugins
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxSerializationGradlePlugin = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
androidKotlinMultiplatformLibraryGradlePlugin = { module = "com.android.kotlin.multiplatform.library:com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "androidGradlePlugin" }

# kotlin
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# kotlinx
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

# ktor
ktorServerWebSockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktorServerTestHost = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientWebSockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktorClientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# logging
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

[bundles]
gradlePlugins = [
    "kotlinGradlePlugin",
    "kotlinxSerializationGradlePlugin",
    "androidKotlinMultiplatformLibraryGradlePlugin"
]
ktorClient = [
    "ktorClientCore",
    "ktorClientCio",
    "ktorClientWebSockets",
    "ktorSerializationKotlinxJson",
    "ktorClientLogging"
]

[plugins]
# kotlin
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinDsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlinDsl" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# android
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }

# conventions
multiplatform = { id = "multiplatform" }
serialization = { id = "serialization" }
