name: ABI Check

on:
  pull_request:
    paths:
      - 'jetwhale-host-sdk/**'
      - 'jetwhale-agent-sdk/**'
      - 'jetwhale-protocol/core/**'
      - 'jetwhale-protocol/agent/**'
      - 'jetwhale-protocol/host/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-legacy-abi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java

      - name: Run ABI check
        run: ./gradlew checkLegacyAbi
