name: ABI Check

on:
  push:
  pull_request:
    paths:
      - 'jetwhale-host-sdk/**'
      - 'jetwhale-agent-sdk/**'
      - 'jetwhale-annotations/**'
      - 'jetwhale-protocol/core/**'
      - 'jetwhale-protocol/agent/**'
      - 'jetwhale-protocol/host/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write

jobs:
  check-legacy-abi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java

      - name: Run ABI check
        run: |
          ./gradlew \
            :jetwhale-host-sdk:checkLegacyAbi \
            :jetwhale-agent-sdk:checkLegacyAbi \
            :jetwhale-annotations:checkLegacyAbi \
            :jetwhale-protocol:core:checkLegacyAbi \
            :jetwhale-protocol:agent:checkLegacyAbi \
            :jetwhale-protocol:host:checkLegacyAbi
