name: Distribute Desktop Application
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  build:
    name: Build Distributable Desktop Application
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macOS-latest
            gradleTask: packageDmg
            artifactGlob: jetwhale-host/app/build/compose/binaries/main/dmg/*.dmg
            artifactName: macos-dmg
          - os: ubuntu-latest
            gradleTask: packageDeb
            artifactGlob: jetwhale-host/app/build/compose/binaries/main/deb/*.deb
            artifactName: linux-deb
          - os: windows-latest
            gradleTask: packageMsi
            artifactGlob: jetwhale-host/app/build/compose/binaries/main/msi/*.msi
            artifactName: windows-msi
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Distributable
        run: ./gradlew :jetwhale-host:app:${{ matrix.gradleTask }}
      - name: Upload Distributable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: ${{ matrix.artifactGlob }}
          if-no-files-found: error
  release:
    name: Create Draft Release and Attach Artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create draft release and attach artifacts
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            dist/**/*.dmg
            dist/**/*.deb
            dist/**/*.msi
          fail_on_unmatched_files: true
